version: '3.8'
services:
  #nginx:
  # image: nginx:latest
  # ports:
  # - 80:80
  # - 443:443
  # volumes:
  # - /etc/nginx/sites-available/default:/etc/nginx/conf.d/default.conf:rw
  # - ./CA/certificate.crt:/home/ubuntu/CA/certificate.crt:ro
  # - ./CA/private.key:/home/ubuntu/CA/private.key:ro
  # - ./CA/ca_bundle.crt:/home/ubuntu/CA/ca_bundle.crt:ro
  # privileged: true
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: happy1234
      MYSQL_DATABASE: Canchu
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - canchu
  redis:
    image:
      redis:latest
      #volumes:
      #- /etc/redis/redis.conf:/redis-config/redis.conf:ro
      #command: ["redis-server","/redis-config/redis.conf"]
    container_name: redis_container
    ports:
      - 6379:6379
    networks:
      - canchu

        #privileged: true
  canchu:
    image: canchu-server
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    networks:
      - canchu
volumes:
  mysql_data:
networks:
  canchu:
    driver: bridge
