name: Canchu CI
on:
  push:
    branches: [week_5_part_2]
    tags:
      - '*'

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: get tag
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - name: Check Context Directory
        run: ls -R
      - name: Build and push Dockerfile
        uses: docker/build-push-action@v3
        with:
          context: ./students/pei-tung/Canchu/
          file: ./students/pei-tung/Canchu/Dockerfile
          push: true
          no-cache: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dockerfile:${{ steps.vars.outputs.tag }}
      - name: Set up Docker Compose
        run: docker-compose --version
      - name: Build and push docker-compose.yml
        run: |
          docker-compose -f ./students/pei-tung/Canchu/docker-compose.yml build
          docker-compose -f ./students/pei-tung/Canchu/docker-compose.yml push
  deploy:
    # depends on build_and_push_image job
    needs: build_and_push_image
    runs-on: ubuntu-latest
    steps:
      - name: deploy to ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/dockerfile:${{ steps.vars.outputs.tag }}
            docker-compose -f ./students/pei-tung/Canchu/docker-compose.yml stop
            docker-compose -f ./students/pei-tung/Canchu/docker-compose.yml rm -f
            docker-compose -f ./students/pei-tung/Canchu/docker-compose.yml up -d
