name: Canchu CI
on:
  push:
    branches: [week_5_part_2]
    tags:
      - '*'

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create env file
        run: |
          touch .env
          echo "DATABASE_HOST=${DATABASE_HOST}" >> .env
          echo "DATABASE_USER=${DATABASE_USER}" >> .env
          echo "DATABASE_PASSWORD=${DATABASE_PASSWORD}"  >> .env
          echo "DATABASE_NAME=${DATABASE_NAME}" >> .env
          echo "JWT_KEY=${JWT_KEY}" >> .env
          echo "FACEBOOK_APP_ID=${FACEBOOK_APP_ID}" >> .env
          echo "FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}" >> .env
          echo "CONTAINER_DATABASE_HOST=${CONTAINER_DATABASE_HOST}" >> .env
          echo "REDIS_URL=${REDIS_URL}" >> .env
        env:
          ENV_FILE_PATH: ./students/pei-tung/Canchu/app
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Dockerfile
        uses: docker/build-push-action@v3
        with:
          context: ./students/pei-tung/Canchu/
          file: ./students/pei-tung/Canchu/Dockerfile
          push: true
          no-cache: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/canchu-server
  deploy:
    # depends on build_and_push_image job
    needs: build_and_push_image
    runs-on: ubuntu-latest
    steps:
      - name: deploy to ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd Campus-Summer-Back-End/students/pei-tung/Canchu
            docker-compose  stop
            docker-compose rm
            git pull
            docker build -t canchu-server .
            docker-compose up -d
